---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume-aws
spec:
  containers:
  - name: nginx
    image: nginx
    startupProbe:
      exec:
        command:
        - touch
        - /usr/share/nginx/html/index.html
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: site-volume
  volumes:
  - name: site-volume
    persistentVolumeClaim:
      claimName: pvc-aws
